// DO NOT EDIT: Generated by config/update_conditions.ts
import "#kvstore/byte_range/register";
import "#kvstore/gcs/register";
import "#kvstore/gzip/register";
import "#kvstore/http/register_backend";
import "#kvstore/icechunk/register_backend";
import "#kvstore/middleauth/register_backend";
import "#kvstore/ngauth/register";
import "#kvstore/ocdbt/register_backend";
import "#kvstore/s3/register_backend";
import "#kvstore/zip/register_backend";
