version: "1"
env:
  PULL_INTERVAL: 1209600 # every two weeks
rules:
  - base: ndmaster
    upstream: google:master
    mergeMethod: merge
    reviewers: 
      - hannahgooden
      - j6k4m8
      - sandyhider
      - movestill
