environment:
    matrix:
      - PYTHON_VERSION: 3.5
        MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy pytest"
  - activate test-environment

build_script:
  - cd python
  - pip install -e .

test_script:
  - cd tests
  - pytest -vv
