root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - "import"
settings:
  "import/parsers":
    "@typescript-eslint/parser": [".ts", ".tsx"]
  "import/resolver":
    "typescript":
    "node":
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:import/recommended"
rules:
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/no-inferrable-types": "off"
  "@typescript-eslint/no-this-alias": "off"
  "@typescript-eslint/no-empty-function": "off"
  "@typescript-eslint/no-empty-interface": "off"
  "prefer-const":
    - "error"
    - destructuring: "all"
  "no-constant-condition": "off"
  "@typescript-eslint/no-unused-vars":
    - "error"
    - argsIgnorePattern: "^_"
      ignoreRestSiblings: true
  "@typescript-eslint/ban-types":
    - "error"
    - types:
        # unban Function
        "Function": false
      extendDefaults: true
  "no-unsafe-finally": "off"
  "require-yield": "off"
  "no-inner-declarations": "off"
  "import/no-named-as-default": "off"
  "import/no-named-as-default-member": "off"
  "import/no-cycle": "error"
  "@typescript-eslint/consistent-type-imports": "error"
  "import/no-unresolved": "error"
  "import/no-extraneous-dependencies": "error"
  "import/first": "error"
  "import/order":
    - "error"
    - groups:
        - "builtin"
        - "external"
        - "internal"
      alphabetize:
        order: "asc"
        orderImportKind: "asc"
overrides:
  - files:
      - "src/**/*"
    rules:
      "no-restricted-imports":
        - "error"
        - patterns:
            - group:
                - "./"
                - "../"
              message: "Relative imports are not allowed."
