#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "matplotlib",
#     "numpy",
#     "tensorstore",
# ]
# ///
"""Generate src/webgl/colormaps.zarr/ as a Zarr v3 array from matplotlib.

The array has shape (N, 256, 3) uint8 where N is the number of colormaps
declared in NAMES below. Each slice colormaps[i, :, :] is the 256x3 RGB
LUT for the colormap whose name is `attributes["colormap_names"][i]`. The
order MUST match COLORMAP_BIN_NAMES in the generated TS file consumed by
src/webgl/colormaps.ts.

The array is stored as a single uncompressed chunk (chunk_shape == shape)
with just the `bytes` codec, so the chunk file at c/0/0/0 contains the
raw uint8 bytes in C-order. The JS bundle fetches that file directly via
`new URL("./colormaps.zarr/c/0/0/0", import.meta.url)` and computes
per-colormap byte offsets client-side; zarr.json is not fetched at
runtime (it lives alongside the chunk only for external tools that want
to open the directory as a Zarr v3 array).

This script also writes src/webgl/colormap_names_generated.ts, the TS
literal-tuple source of truth for `ColormapBinName` / `ColormapName`
types.

Both outputs are gitignored; they are produced at build time by the
`generate-colormaps` npm script (invoked via `prebuild`/`predev-server`/
`prebuild-python` hooks and from build_tools/build-package.ts before
`npm pack` runs).

Usage (uv reads the PEP 723 header above to set up the env automatically):
    uv run --no-project build_tools/generate_colormaps_zarr.py
"""

from __future__ import annotations

import pathlib
import shutil
import sys

# Source of truth for the colormap list. Order is preserved in both the
# zarr's `attributes.colormap_names` AND in the generated TS tuples
# written to src/webgl/colormap_names_generated.ts (consumed by
# colormaps.ts).
NAMES = (
    "grayscale",
    "viridis",
    "plasma",
    "cividis",
    "magma",
    "coolwarm",
    "rdbu",
    "turbo",
    "cubehelix",
    "oranges",
    "jet",
)

# Names that are present in the zarr (and reachable via free GLSL functions
# like `colormapJet`) but excluded from the user-facing #uicontrol colormap
# dropdown.
COMPAT_ONLY = frozenset({"jet"})

# Aliases for names that differ between matplotlib and Neuroglancer.
ALIASES = {
    "grayscale": "gray",
    "rdbu": "RdBu",
    "oranges": "Oranges",
}


def write_names_ts(target: pathlib.Path) -> None:
    """Write the TS source-of-truth file consumed by src/webgl/colormaps.ts.

    Emits two `as const` tuples — the full bin list and the user-facing
    subset — so TypeScript can derive literal-union types via
    `(typeof COLORMAP_BIN_NAMES)[number]`.
    """
    user_facing = tuple(n for n in NAMES if n not in COMPAT_ONLY)
    lines = [
        "/**",
        " * @license",
        " * Copyright 2026 Google Inc.",
        ' * Licensed under the Apache License, Version 2.0 (the "License");',
        " * you may not use this file except in compliance with the License.",
        " * You may obtain a copy of the License at",
        " *",
        " *      http://www.apache.org/licenses/LICENSE-2.0",
        " *",
        " * Unless required by applicable law or agreed to in writing, software",
        ' * distributed under the License is distributed on an "AS IS" BASIS,',
        " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
        " * See the License for the specific language governing permissions and",
        " * limitations under the License.",
        " */",
        "",
        "// AUTOGENERATED by build_tools/generate_colormaps_zarr.py — do not edit.",
        "// Source of truth: the NAMES tuple in that script. This file is",
        "// gitignored and regenerated by the `generate-colormaps` npm script.",
        "",
        "// Full list of colormaps present in colormaps.zarr, in N-axis order.",
        "// Includes back-compat-only names reachable via free GLSL functions",
        "// (e.g. `colormapJet`) but hidden from the user-facing dropdown.",
        "export const COLORMAP_BIN_NAMES = [",
        *[f'  "{name}",' for name in NAMES],
        "] as const;",
        "",
        "// User-facing subset shown in the #uicontrol colormap dropdown.",
        "export const COLORMAP_NAMES = [",
        *[f'  "{name}",' for name in user_facing],
        "] as const;",
        "",
    ]
    target.write_text("\n".join(lines))


def main() -> int:
    # matplotlib/numpy/tensorstore aren't installed in the mypy nox session's
    # env (they're supplied at runtime via the PEP 723 header above), so
    # silence the import-not-found warnings here.
    try:
        import matplotlib  # type: ignore[import-not-found]
        import numpy as np  # type: ignore[import-not-found]
        import tensorstore as ts  # type: ignore[import-not-found]
    except ImportError as e:
        print(f"missing dependency: {e}", file=sys.stderr)
        return 1

    try:
        cmaps = matplotlib.colormaps
    except AttributeError:  # matplotlib < 3.7
        import matplotlib.cm as cmaps  # type: ignore

    t = np.linspace(0.0, 1.0, 256)
    # Build (N, 256, 3) uint8 array. Each colormap's 256 RGB rows are a
    # contiguous 768-byte block in C-order, matching the JS-side accessor.
    array = np.zeros((len(NAMES), 256, 3), dtype=np.uint8)
    for i, name in enumerate(NAMES):
        mpl_name = ALIASES.get(name, name)
        cmap = (
            cmaps.get_cmap(mpl_name) if hasattr(cmaps, "get_cmap") else cmaps[mpl_name]
        )
        rgb = cmap(t)[:, :3]  # (256, 3) floats in [0, 1]
        array[i, :, :] = np.clip(np.rint(rgb * 255.0), 0, 255).astype(np.uint8)

    target_dir = (
        pathlib.Path(__file__).resolve().parent.parent
        / "src"
        / "webgl"
        / "colormaps.zarr"
    )
    # Wipe any existing zarr.json + chunk tree so this script is idempotent.
    # The README.md (if any) is preserved.
    if (target_dir / "zarr.json").exists():
        (target_dir / "zarr.json").unlink()
    chunk_root = target_dir / "c"
    if chunk_root.exists():
        shutil.rmtree(chunk_root)

    # One outer chunk of full-array shape = a single shard at c/0/0/0.
    # The sharding codec subdivides that shard into one inner chunk per
    # colormap (shape (1, 256, 3)). Inner data codec is `bytes` (uncompressed
    # uint8). Index codec chain is `bytes` + `crc32c` (the default).
    spec = {
        "driver": "zarr3",
        "kvstore": {"driver": "file", "path": str(target_dir)},
        "metadata": {
            "shape": list(array.shape),
            "data_type": "uint8",
            "chunk_grid": {
                "name": "regular",
                "configuration": {"chunk_shape": list(array.shape)},
            },
            "chunk_key_encoding": {
                "name": "default",
                "configuration": {"separator": "/"},
            },
            # Single uncompressed chunk: the `bytes` codec on uint8 is a
            # no-op, so the chunk file at c/0/0/0 contains the raw bytes of
            # the (N, 256, 3) array in C-order. The JS bundle fetches that
            # file directly via `new URL(...)` without parsing zarr.json or
            # any codec/sharding machinery at runtime.
            "codecs": [
                {"name": "bytes", "configuration": {"endian": "little"}},
            ],
            "fill_value": 0,
            "dimension_names": ["colormap", "entry", "channel"],
            "attributes": {
                "colormap_names": list(NAMES),
            },
        },
        "create": True,
    }
    store = ts.open(spec).result()
    store.write(array).result()

    # Round-trip self-check.
    read = ts.open(
        {
            "driver": "zarr3",
            "kvstore": {"driver": "file", "path": str(target_dir)},
        }
    ).result()
    assert tuple(read.shape) == array.shape, (read.shape, array.shape)
    assert read.dtype.numpy_dtype == np.uint8, read.dtype
    round_tripped_names = read.spec().to_json()["metadata"]["attributes"][
        "colormap_names"
    ]
    assert tuple(round_tripped_names) == NAMES, (round_tripped_names, NAMES)

    # Write the TS literal-tuple file consumed by src/webgl/colormaps.ts.
    names_ts_target = (
        pathlib.Path(__file__).resolve().parent.parent
        / "src"
        / "webgl"
        / "colormap_names_generated.ts"
    )
    write_names_ts(names_ts_target)

    print(f"wrote {target_dir} ({len(NAMES)} colormaps, shape {tuple(array.shape)})")
    print(f"wrote {names_ts_target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
