/**
 * @license
 * Copyright 2024 Ichnaea.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file Support for rendering oriented (rotatable) bounding box annotations.
 *
 * Unlike the axis-aligned bounding box, this box carries a quaternion
 * `orientation`, so its 8 corners are computed as
 * `center + R(orientation) * (sign * extents/2)` in the 3D display subspace.
 * The quaternion is supplied as a per-instance vertex attribute and converted
 * to a rotation matrix in the vertex shader.
 */

import type { OrientedBoundingBox } from "#src/annotation/index.js";
import { AnnotationType } from "#src/annotation/index.js";
import type {
  AnnotationRenderContext,
  AnnotationShaderGetter,
} from "#src/annotation/type_handler.js";
import {
  AnnotationRenderHelper,
  registerAnnotationTypeRenderHandler,
} from "#src/annotation/type_handler.js";
import type { SliceViewPanelRenderContext } from "#src/sliceview/renderlayer.js";
import {
  boundingBoxCrossSectionVertexIndices,
  vertexBasePositions,
} from "#src/sliceview/bounding_box_shader_helper.js";
import { tile2dArray } from "#src/util/array.js";
import {
  mat3,
  quat,
  transformVectorByMat4Transpose,
  vec3,
} from "#src/util/geom.js";
import { CORNERS_PER_BOX, EDGES_PER_BOX } from "#src/webgl/bounding_box.js";
import { GLBuffer } from "#src/webgl/buffer.js";
import {
  defineCircleShader,
  drawCircles,
  initializeCircleShader,
  VERTICES_PER_CIRCLE,
} from "#src/webgl/circles.js";
import {
  defineLineShader,
  drawLines,
  initializeLineShader,
  VERTICES_PER_LINE,
} from "#src/webgl/lines.js";
import type { ShaderBuilder, ShaderProgram } from "#src/webgl/shader.js";
import { defineVectorArrayVertexShaderInput } from "#src/webgl/shader_lib.js";
import { defineVertexId, VertexIdHelper } from "#src/webgl/vertex_id.js";

// Pick-ID layout per instance. The box-geometry offsets (corners/edges/faces)
// match the axis-aligned box so the existing snap/representative-point helpers
// stay familiar; the gizmo handles are appended after.
const FULL_OBJECT_PICK_OFFSET = 0;
const CORNERS_PICK_OFFSET = FULL_OBJECT_PICK_OFFSET + 1;
const EDGES_PICK_OFFSET = CORNERS_PICK_OFFSET + CORNERS_PER_BOX;
const FACES_PICK_OFFSET = EDGES_PICK_OFFSET + EDGES_PER_BOX; // 6 extrude caps
const ROTATE_RING_PICK_OFFSET = FACES_PICK_OFFSET + 6; // 3 rings
const ARCBALL_PICK_OFFSET = ROTATE_RING_PICK_OFFSET + 3; // 1 free-rotate sphere
const TRANSLATE_AXIS_PICK_OFFSET = ARCBALL_PICK_OFFSET + 1; // 3 tripod arrows
const CENTER_BALL_PICK_OFFSET = TRANSLATE_AXIS_PICK_OFFSET + 3; // 1 free translate
export const ORIENTED_BBOX_PICK_IDS_PER_INSTANCE = CENTER_BALL_PICK_OFFSET + 1;

export {
  FULL_OBJECT_PICK_OFFSET,
  CORNERS_PICK_OFFSET,
  EDGES_PICK_OFFSET,
  FACES_PICK_OFFSET,
  ROTATE_RING_PICK_OFFSET,
  ARCBALL_PICK_OFFSET,
  TRANSLATE_AXIS_PICK_OFFSET,
  CENTER_BALL_PICK_OFFSET,
};

// The 12 edges of the unit cube [0,1]^3. Each row is:
//   cornerA (xyz in {0,1}), cornerB (xyz in {0,1}), edge pick index.
// Generated by walking, for each axis, the 4 edges parallel to it.
function makeEdgeBoxCornerOffsetData(): Float32Array {
  const data: number[] = [];
  let edgeIndex = 0;
  for (let axis = 0; axis < 3; ++axis) {
    const u = (axis + 1) % 3;
    const v = (axis + 2) % 3;
    for (let i = 0; i < 2; ++i) {
      for (let j = 0; j < 2; ++j) {
        const a = [0, 0, 0];
        a[u] = i;
        a[v] = j;
        const b = [...a];
        b[axis] = 1;
        data.push(
          a[0],
          a[1],
          a[2],
          b[0],
          b[1],
          b[2],
          EDGES_PICK_OFFSET + edgeIndex,
        );
        ++edgeIndex;
      }
    }
  }
  return Float32Array.from(data);
}

const edgeBoxCornerOffsetData = makeEdgeBoxCornerOffsetData();

// GLSL: build a column-major rotation matrix from a unit quaternion (x,y,z,w),
// matching gl-matrix `mat3.fromQuat` so CPU and GPU agree.
const glsl_quatToMat3 = `
mat3 quatToMat3(vec4 q) {
  float x = q.x, y = q.y, z = q.z, w = q.w;
  float x2 = x + x, y2 = y + y, z2 = z + z;
  float xx = x * x2, xy = x * y2, xz = x * z2;
  float yy = y * y2, yz = y * z2, zz = z * z2;
  float wx = w * x2, wy = w * y2, wz = w * z2;
  return mat3(
    1.0 - (yy + zz), xy + wz,         xz - wy,
    xy - wz,         1.0 - (xx + zz), yz + wx,
    xz + wy,         yz - wx,         1.0 - (xx + yy));
}
`;

abstract class RenderHelper extends AnnotationRenderHelper {
  defineShader(builder: ShaderBuilder) {
    defineVertexId(builder);
    const { rank } = this;
    // center + extents in model coordinates (getBounds0/getBounds1).
    defineVectorArrayVertexShaderInput(
      builder,
      "float",
      WebGL2RenderingContext.FLOAT,
      /*normalized=*/ false,
      "Bounds",
      rank,
      2,
    );
    // orientation quaternion [x, y, z, w] (getOrientation0).
    defineVectorArrayVertexShaderInput(
      builder,
      "float",
      WebGL2RenderingContext.FLOAT,
      /*normalized=*/ false,
      "Orientation",
      4,
      1,
    );
    builder.addVertexCode(glsl_quatToMat3);
    // Shared helper: produce the rotated subspace position for a corner whose
    // offset components are each in {0, 1}.
    builder.addVertexCode(`
vec3 orientedCornerPosition(vec3 cornerOffset) {
  float center[${rank}] = getBounds0();
  float extents[${rank}] = getBounds1();
  vec3 subCenter = projectModelVectorToSubspace(center);
  vec3 subExtents = projectModelVectorToSubspace(extents);
  vec3 halfExtents = abs(subExtents) * 0.5;
  float q[4] = getOrientation0();
  mat3 R = quatToMat3(vec4(q[0], q[1], q[2], q[3]));
  vec3 localOffset = (cornerOffset * 2.0 - 1.0) * halfExtents;
  return subCenter + R * localOffset;
}
float orientedClipCoefficient() {
  float center[${rank}] = getBounds0();
  float extents[${rank}] = getBounds1();
  float modelLower[${rank}];
  float modelUpper[${rank}];
  for (int i = 0; i < ${rank}; ++i) {
    float halfExtent = extents[i] * 0.5;
    modelLower[i] = center[i] - halfExtent;
    modelUpper[i] = center[i] + halfExtent;
  }
  return getMaxSubspaceClipCoefficient(modelLower, modelUpper);
}
float ng_lineWidth;
`);
  }

  private vertexIdHelper = this.registerDisposer(VertexIdHelper.get(this.gl));

  enable(
    shaderGetter: AnnotationShaderGetter,
    context: AnnotationRenderContext,
    callback: (shader: ShaderProgram) => void,
  ) {
    super.enable(shaderGetter, context, (shader) => {
      const { gl } = this;
      const boundsBinder = shader.vertexShaderInputBinders.Bounds;
      const orientationBinder = shader.vertexShaderInputBinders.Orientation;
      boundsBinder.enable(1);
      orientationBinder.enable(1);
      gl.bindBuffer(WebGL2RenderingContext.ARRAY_BUFFER, context.buffer.buffer);
      boundsBinder.bind(this.geometryDataStride, context.bufferOffset);
      // The quaternion follows the two rank-length vectors in each instance.
      orientationBinder.bind(
        this.geometryDataStride,
        context.bufferOffset + 2 * 4 * this.rank,
      );
      const { vertexIdHelper } = this;
      vertexIdHelper.enable();
      callback(shader);
      vertexIdHelper.disable();
      orientationBinder.disable();
      boundsBinder.disable();
    });
  }
}

class PerspectiveViewRenderHelper extends RenderHelper {
  private edgeBoxCornerOffsetsBuffer = this.registerDisposer(
    GLBuffer.fromData(
      this.gl,
      tile2dArray(
        edgeBoxCornerOffsetData,
        /*majorDimension=*/ 7,
        /*minorTiles=*/ 1,
        /*majorTiles=*/ VERTICES_PER_LINE,
      ),
    ),
  );

  private edgeShaderGetter = this.getDependentShader(
    "annotation/orientedBoundingBox/projection/border",
    (builder: ShaderBuilder) => {
      this.defineShader(builder);
      defineLineShader(builder);

      builder.addAttribute("highp vec3", "aBoxCornerOffset1");
      // Last component of aBoxCornerOffset2 is the edge pick index.
      builder.addAttribute("highp vec4", "aBoxCornerOffset2");
      builder.addVarying("highp float", "vClipCoefficient");

      builder.setVertexMain(`
vClipCoefficient = orientedClipCoefficient();
if (vClipCoefficient == 0.0) {
  gl_Position = vec4(2.0, 0.0, 0.0, 1.0);
  return;
}
vec3 endpointA = orientedCornerPosition(aBoxCornerOffset1);
vec3 endpointB = orientedCornerPosition(aBoxCornerOffset2.xyz);
ng_lineWidth = 1.0;
${this.invokeUserMain}
vColor = vec4(uColor, 1.0);
emitLine(uModelViewProjection * vec4(endpointA, 1.0),
         uModelViewProjection * vec4(endpointB, 1.0),
         ng_lineWidth);
${this.setPartIndex(builder, "uint(aBoxCornerOffset2.w)")};
`);
      builder.setFragmentMain(`
emitAnnotation(vec4(vColor.rgb, getLineAlpha() * vClipCoefficient));
`);
    },
  );

  private boxCornerOffsetsBuffer = this.registerDisposer(
    GLBuffer.fromData(
      this.gl,
      tile2dArray(
        vertexBasePositions,
        /*majorDimension=*/ 3,
        /*minorTiles=*/ 1,
        /*majorTiles=*/ VERTICES_PER_CIRCLE,
      ),
    ),
  );

  private cornerShaderGetter = this.getDependentShader(
    "annotation/orientedBoundingBox/projection/corner",
    (builder: ShaderBuilder) => {
      this.defineShader(builder);
      defineCircleShader(builder, this.targetIsSliceView);

      builder.addAttribute("highp vec3", "aBoxCornerOffset");
      builder.addVarying("highp float", "vClipCoefficient");
      builder.setVertexMain(`
vClipCoefficient = orientedClipCoefficient();
if (vClipCoefficient == 0.0) {
  gl_Position = vec4(2.0, 0.0, 0.0, 1.0);
  return;
}
vec3 vertexPosition = orientedCornerPosition(aBoxCornerOffset);
ng_lineWidth = 6.0;
${this.invokeUserMain}
vColor = vec4(uColor, 1.0);
emitCircle(uModelViewProjection * vec4(vertexPosition, 1.0), ng_lineWidth, 0.0);
uint cornerIndex = uint(aBoxCornerOffset.x + aBoxCornerOffset.y * 2.0 + aBoxCornerOffset.z * 4.0);
uint cornerPickOffset = ${CORNERS_PICK_OFFSET}u + cornerIndex;
${this.setPartIndex(builder, "cornerPickOffset")};
`);
      builder.setFragmentMain(`
vec4 borderColor = vec4(0.0, 0.0, 0.0, 1.0);
vec4 color = getCircleColor(vColor, borderColor);
color.a *= vClipCoefficient;
emitAnnotation(color);
`);
    },
  );

  drawEdges(context: AnnotationRenderContext) {
    const { gl } = this;
    this.enable(this.edgeShaderGetter, context, (shader) => {
      const aBoxCornerOffset1 = shader.attribute("aBoxCornerOffset1");
      const aBoxCornerOffset2 = shader.attribute("aBoxCornerOffset2");
      this.edgeBoxCornerOffsetsBuffer.bindToVertexAttrib(
        aBoxCornerOffset1,
        /*components=*/ 3,
        /*attributeType=*/ WebGL2RenderingContext.FLOAT,
        /*normalized=*/ false,
        /*stride=*/ 4 * 7,
        /*offset=*/ 0,
      );
      this.edgeBoxCornerOffsetsBuffer.bindToVertexAttrib(
        aBoxCornerOffset2,
        /*components=*/ 4,
        /*attributeType=*/ WebGL2RenderingContext.FLOAT,
        /*normalized=*/ false,
        /*stride=*/ 4 * 7,
        /*offset=*/ 4 * 3,
      );
      initializeLineShader(
        shader,
        context.renderContext.projectionParameters,
        /*featherWidthInPixels=*/ 1,
      );
      drawLines(gl, EDGES_PER_BOX, context.count);
      gl.disableVertexAttribArray(aBoxCornerOffset1);
      gl.disableVertexAttribArray(aBoxCornerOffset2);
    });
  }

  drawCorners(context: AnnotationRenderContext) {
    const { gl } = this;
    this.enable(this.cornerShaderGetter, context, (shader) => {
      const aBoxCornerOffset = shader.attribute("aBoxCornerOffset");
      this.boxCornerOffsetsBuffer.bindToVertexAttrib(
        aBoxCornerOffset,
        /*components=*/ 3,
        /*attributeType=*/ WebGL2RenderingContext.FLOAT,
        /*normalized=*/ false,
      );
      initializeCircleShader(
        shader,
        context.renderContext.projectionParameters,
        { featherWidthInPixels: 0 },
      );
      drawCircles(shader.gl, CORNERS_PER_BOX, context.count);
      gl.disableVertexAttribArray(aBoxCornerOffset);
    });
  }

  draw(context: AnnotationRenderContext) {
    this.drawEdges(context);
    this.drawCorners(context);
  }
}

const sliceTempVec3 = vec3.create();
const sliceTempVec3b = vec3.create();

/**
 * Slice-view rendering draws the true cross-section: the convex polygon where
 * the viewport plane cuts the oriented box (up to 6 vertices). The Salama-Kolb
 * box/plane intersection is done in the box's LOCAL (axis-aligned) frame by
 * transforming the slice plane with the per-instance rotation, so the
 * front-vertex ordering is correct per box rather than per draw call.
 */
class SliceViewRenderHelper extends RenderHelper {
  private defineCrossSection(builder: ShaderBuilder) {
    const { rank } = this;
    builder.addUniform("highp vec3", "uPlaneNormal");
    builder.addUniform("highp float", "uPlaneDistance");
    builder.addUniform("highp vec3", "uVertexBasePosition", 8);
    // All 8 front-vertex orderings (24 candidate edges each), indexed in-shader.
    builder.addUniform("highp ivec2", "uVertexIndexAll", 8 * 24);
    builder.addInitializer((shader) => {
      shader.gl.uniform3fv(
        shader.uniform("uVertexBasePosition"),
        vertexBasePositions,
      );
      shader.gl.uniform2iv(
        shader.uniform("uVertexIndexAll"),
        boundingBoxCrossSectionVertexIndices,
      );
    });
    builder.addVertexCode(`
vec3 orientedCrossSectionVertex(int vertexIndex) {
  float center[${rank}] = getBounds0();
  float extents[${rank}] = getBounds1();
  vec3 subCenter = projectModelVectorToSubspace(center);
  vec3 subExtents = projectModelVectorToSubspace(extents);
  vec3 halfExtents = abs(subExtents) * 0.5;
  float q[4] = getOrientation0();
  mat3 R = quatToMat3(vec4(q[0], q[1], q[2], q[3]));
  // Transform the slice plane into the box's local (axis-aligned) frame.
  vec3 localN = uPlaneNormal * R;                   // R^T * N (R is orthonormal)
  float localD = uPlaneDistance - dot(subCenter, uPlaneNormal);
  int fv = 0;
  if (localN.x < 0.0) fv += 1;
  if (localN.y < 0.0) fv += 2;
  if (localN.z < 0.0) fv += 4;
  for (int e = 0; e < 4; ++e) {
    ivec2 vidx = uVertexIndexAll[fv * 24 + vertexIndex * 4 + e];
    vec3 lA = (uVertexBasePosition[vidx.x] * 2.0 - 1.0) * halfExtents;
    vec3 lB = (uVertexBasePosition[vidx.y] * 2.0 - 1.0) * halfExtents;
    vec3 dir = lB - lA;
    float denom = dot(dir, localN);
    if (abs(denom) > 1e-3) {
      float lambda = (localD - dot(lA, localN)) / denom;
      if (lambda >= -1e-3 && lambda <= 1.0 + 1e-3) {
        lambda = clamp(lambda, 0.0, 1.0);
        return subCenter + R * (lA + lambda * dir);
      }
    }
  }
  return subCenter;  // plane misses box -> degenerate (zero-area) polygon
}
`);
  }

  private faceShaderGetter = this.getDependentShader(
    "annotation/orientedBoundingBox/crossSection/border",
    (builder: ShaderBuilder) => {
      this.defineShader(builder);
      this.defineCrossSection(builder);
      defineLineShader(builder);
      builder.setVertexMain(`
int vertexIndex1 = gl_VertexID / ${VERTICES_PER_LINE};
int vertexIndex2 = vertexIndex1 == 5 ? 0 : vertexIndex1 + 1;
vec3 p1 = orientedCrossSectionVertex(vertexIndex1);
vec3 p2 = orientedCrossSectionVertex(vertexIndex2);
ng_lineWidth = 1.0;
${this.invokeUserMain}
vColor = vec4(uColor, 1.0);
emitLine(uModelViewProjection * vec4(p1, 1.0),
         uModelViewProjection * vec4(p2, 1.0),
         ng_lineWidth);
${this.setPartIndex(builder)};
`);
      builder.setFragmentMain(`
emitAnnotation(vec4(vColor.rgb, vColor.a * getLineAlpha()));
`);
    },
  );

  private setPlane(
    shader: ShaderProgram,
    context: AnnotationRenderContext & {
      renderContext: SliceViewPanelRenderContext;
    },
  ) {
    const { gl } = this;
    const projectionParameters =
      context.renderContext.sliceView.projectionParameters.value;
    const localPlaneNormal = transformVectorByMat4Transpose(
      sliceTempVec3,
      projectionParameters.viewportNormalInGlobalCoordinates,
      context.renderSubspaceModelMatrix,
    );
    vec3.normalize(localPlaneNormal, localPlaneNormal);
    const planeDistance = vec3.dot(
      vec3.transformMat4(
        sliceTempVec3b,
        projectionParameters.centerDataPosition,
        context.renderSubspaceInvModelMatrix,
      ),
      localPlaneNormal,
    );
    gl.uniform3fv(shader.uniform("uPlaneNormal"), localPlaneNormal);
    gl.uniform1f(shader.uniform("uPlaneDistance"), planeDistance);
  }

  draw(
    context: AnnotationRenderContext & {
      renderContext: SliceViewPanelRenderContext;
    },
  ) {
    this.enable(this.faceShaderGetter, context, (shader) => {
      this.setPlane(shader, context);
      initializeLineShader(
        shader,
        context.renderContext.projectionParameters,
        /*featherWidthInPixels=*/ 1.0,
      );
      drawLines(shader.gl, 6, context.count);
    });
  }
}

function snapPositionToCorner(
  position: Float32Array,
  center: Float32Array,
  extents: Float32Array,
  orientation: Float32Array,
  cornerIndex: number,
) {
  const rank = position.length;
  const r = mat3.fromQuat(mat3.create(), orientation as unknown as quat);
  // Decode the corner sign pattern from the corner index (x + 2y + 4z).
  const sx = cornerIndex & 1 ? 1 : -1;
  const sy = cornerIndex & 2 ? 1 : -1;
  const sz = cornerIndex & 4 ? 1 : -1;
  const local = [
    (sx * (extents[0] ?? 0)) / 2,
    (sy * (extents[1] ?? 0)) / 2,
    (sz * (extents[2] ?? 0)) / 2,
  ];
  // Rotate the local corner into world space (subspace == first 3 model dims).
  for (let i = 0; i < Math.min(3, rank); ++i) {
    position[i] =
      center[i] + r[i] * local[0] + r[i + 3] * local[1] + r[i + 6] * local[2];
  }
}

registerAnnotationTypeRenderHandler<OrientedBoundingBox>(
  AnnotationType.ORIENTED_BOUNDING_BOX,
  {
    sliceViewRenderHelper: SliceViewRenderHelper,
    perspectiveViewRenderHelper: PerspectiveViewRenderHelper,
    defineShaderNoOpSetters() {
      // This type introduces no new shader setter functions (it sets vColor
      // directly from uColor), so other annotation types' shaders need no
      // no-op stubs from us.
    },
    pickIdsPerInstance: ORIENTED_BBOX_PICK_IDS_PER_INSTANCE,
    snapPosition(position, data, offset, partIndex) {
      const rank = position.length;
      // Layout: center (rank), extents (rank), orientation (4).
      const center = new Float32Array(data, offset, rank);
      const extents = new Float32Array(data, offset + rank * 4, rank);
      const orientation = new Float32Array(data, offset + rank * 8, 4);
      if (partIndex >= CORNERS_PICK_OFFSET && partIndex < EDGES_PICK_OFFSET) {
        snapPositionToCorner(
          position,
          center,
          extents,
          orientation,
          partIndex - CORNERS_PICK_OFFSET,
        );
      }
      // Other parts (faces/handles/full object) keep the picked world position.
    },
    getRepresentativePoint(out, ann) {
      // The drag math in `updateViaRepresentativePoint` works off the box
      // center for every handle, so the center is the representative point.
      out.set(ann.center);
    },
    updateViaRepresentativePoint(
      oldAnnotation: OrientedBoundingBox,
      position: Float32Array,
    ) {
      // Placeholder: translate the whole box so its center follows the drag.
      // Per-handle extrude/rotate semantics are implemented in a later step.
      return { ...oldAnnotation, center: new Float32Array(position) };
    },
  },
);
