name: Build

on:
  push:
    branches:
      - master
    tags:
      - v**
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  # Builds Python package and runs Python tests
  #
  # On ubuntu-latest, this also runs browser-based tests.  On Mac OS and
  # Windows, this only runs tests that do not require a browser, since a working
  # headless WebGL2 implementation is not available on Github actions.
  python-tests:
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.13"
        os:
          - "ubuntu-latest"
          - "windows-2025-vs2026"
          - "macos-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          # Need full history to determine version number.
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: false
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/setup-firefox
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3.24
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - run: uvx nox -s lint format mypy
      - name: Check for dirty working directory
        run: git diff --exit-code
      - name: Run python tests (skip browser tests)
        run: uvx nox -s test -- --skip-browser-tests
        if: ${{ runner.os != 'Linux' }}
      - name: Run python tests (include browser tests)
        run: uvx nox -s test_xvfb -- --browser firefox --timeout=120
        if: ${{ runner.os == 'Linux' }}
      # Verify that editable install works
      - name: Test in editable form
        run: uvx nox -s test_editable
