name: Build preview

on:
  pull_request:

jobs:
  upload:
    strategy:
      matrix:
        node-version:
          - "20.x"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: |
          build_info="{'tag':'$(git describe --always --tags)', 'url':'https://github.com/google/neuroglancer/commit/$(git rev-parse HEAD)', 'timestamp':'$(date)'}"
          npm run build -- --no-typecheck --no-lint --define NEUROGLANCER_BUILD_INFO="${build_info}"
      - name: Upload client as artifact
        uses: actions/upload-artifact@v4
        with:
          name: client
          path: |
            dist/client/*
