name: Deploy Production Neuroglancer

on:
  # Trigger the workflow on push,
  # but only for the master branch
  push:
    branches:
      - ndmaster

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: bahmutov/npm-install@v1
    - run: npm install
    - run: npm run build
    - name: S3 Sync
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' 
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'dist/min'