name: Create pull request from Google latest

on:
  # schedule:
  # - cron: "0 0 19 * *"
  # workflow_dispatch:
  # Trigger the workflow on push,
  # but only for the ndmaster branch
  push:
    branches: hannah/github-actions


jobs:
  create-pr:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Create branch temp-google-merge
    #   uses: peterjgrainger/action-create-branch@v2.0.1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     branch: temp-google-merge

    # - name: Merge google/master -> jhuapl-boss/ndmaster
    #   uses: tgymnich/fork-sync@v1.3
    #   with:
    #     owner: google
    #     head: master
    #     base: ndmaster
    #     github_token: ${{ secrets.GITHUB_TOKEN }} 
    #     auto_approve: false

    - name: Create pull request jhuapl-boss/temp-google-master -> jhuapl-boss/ndmaster
      uses: peter-evans/create-pull-request@v3
      with:
        branch: google:master
        reviewers: hannahgooden 
        token: ${{ secrets.GITHUB_TOKEN }}

